library(shiny)



states <- state.abb
names(states) <- state.name
# TODO: pull AK & HI from world2Hires & reposition on main map
states <- states[!grepl('AK|HI',states)]
states <- append(states,list('United States' = 'all'),after=0)

drgs = list(
  "057 - DEGENERATIVE NERVOUS SYSTEM DISORDERS W/O MCC" = "057",
  "064 - INTRACRANIAL HEMORRHAGE OR CEREBRAL INFARCTION W MCC" = "064",
  "065 - INTRACRANIAL HEMORRHAGE OR CEREBRAL INFARCTION W CC" = "065",
  "065 - INTRACRANIAL HEMORRHAGE OR CEREBRAL INFARCTION W CC OR TPA IN 24 HRS" = "065",
  "066 - INTRACRANIAL HEMORRHAGE OR CEREBRAL INFARCTION W/O CC/MCC" = "066",
  "069 - TRANSIENT ISCHEMIA" = "069",
  "101 - SEIZURES W/O MCC" = "101",
  "176 - PULMONARY EMBOLISM W/O MCC" = "176",
  "177 - RESPIRATORY INFECTIONS & INFLAMMATIONS W MCC" = "177",
  "178 - RESPIRATORY INFECTIONS & INFLAMMATIONS W CC" = "178",
  "189 - PULMONARY EDEMA & RESPIRATORY FAILURE" = "189",
  "190 - CHRONIC OBSTRUCTIVE PULMONARY DISEASE W MCC" = "190",
  "191 - CHRONIC OBSTRUCTIVE PULMONARY DISEASE W CC" = "191",
  "192 - CHRONIC OBSTRUCTIVE PULMONARY DISEASE W/O CC/MCC" = "192",
  "193 - SIMPLE PNEUMONIA & PLEURISY W MCC" = "193",
  "194 - SIMPLE PNEUMONIA & PLEURISY W CC" = "194",
  "195 - SIMPLE PNEUMONIA & PLEURISY W/O CC/MCC" = "195",
  "202 - BRONCHITIS & ASTHMA W CC/MCC" = "202",
  "203 - BRONCHITIS & ASTHMA W/O CC/MCC" = "203",
  "208 - RESPIRATORY SYSTEM DIAGNOSIS W VENTILATOR SUPPORT <96 HOURS" = "208",
  "243 - PERMANENT CARDIAC PACEMAKER IMPLANT W CC" = "243",
  "280 - ACUTE MYOCARDIAL INFARCTION, DISCHARGED ALIVE W MCC" = "280",
  "281 - ACUTE MYOCARDIAL INFARCTION, DISCHARGED ALIVE W CC" = "281",
  "282 - ACUTE MYOCARDIAL INFARCTION, DISCHARGED ALIVE W/O CC/MCC" = "282",
  "291 - HEART FAILURE & SHOCK W MCC" = "291",
  "292 - HEART FAILURE & SHOCK W CC" = "292",
  "293 - HEART FAILURE & SHOCK W/O CC/MCC" = "293",
  "300 - PERIPHERAL VASCULAR DISORDERS W CC" = "300",
  "305 - HYPERTENSION W/O MCC" = "305",
  "308 - CARDIAC ARRHYTHMIA & CONDUCTION DISORDERS W MCC" = "308",
  "309 - CARDIAC ARRHYTHMIA & CONDUCTION DISORDERS W CC" = "309",
  "310 - CARDIAC ARRHYTHMIA & CONDUCTION DISORDERS W/O CC/MCC" = "310",
  "312 - SYNCOPE & COLLAPSE" = "312",
  "313 - CHEST PAIN" = "313",
  "329 - MAJOR SMALL & LARGE BOWEL PROCEDURES W MCC" = "329",
  "330 - MAJOR SMALL & LARGE BOWEL PROCEDURES W CC" = "330",
  "372 - MAJOR GASTROINTESTINAL DISORDERS & PERITONEAL INFECTIONS W CC" = "372",
  "377 - G.I. HEMORRHAGE W MCC" = "377",
  "378 - G.I. HEMORRHAGE W CC" = "378",
  "379 - G.I. HEMORRHAGE W/O CC/MCC" = "379",
  "389 - G.I. OBSTRUCTION W CC" = "389",
  "390 - G.I. OBSTRUCTION W/O CC/MCC" = "390",
  "391 - ESOPHAGITIS, GASTROENT & MISC DIGEST DISORDERS W MCC" = "391",
  "392 - ESOPHAGITIS, GASTROENT & MISC DIGEST DISORDERS W/O MCC" = "392",
  "394 - OTHER DIGESTIVE SYSTEM DIAGNOSES W CC" = "394",
  "419 - LAPAROSCOPIC CHOLECYSTECTOMY W/O C.D.E. W/O CC/MCC" = "419",
  "470 - MAJOR JOINT REPLACEMENT OR REATTACHMENT OF LOWER EXTREMITY W/O MCC" = "470",
  "481 - HIP & FEMUR PROCEDURES EXCEPT MAJOR JOINT W CC" = "481",
  "482 - HIP & FEMUR PROCEDURES EXCEPT MAJOR JOINT W/O CC/MCC" = "482",
  "536 - FRACTURES OF HIP & PELVIS W/O MCC" = "536",
  "552 - MEDICAL BACK PROBLEMS W/O MCC" = "552",
  "563 - FX, SPRN, STRN & DISL EXCEPT FEMUR, HIP, PELVIS & THIGH W/O MCC" = "563",
  "603 - CELLULITIS W/O MCC" = "603",
  "637 - DIABETES W MCC" = "637",
  "638 - DIABETES W CC" = "638",
  "640 - MISC DISORDERS OF NUTRITION,METABOLISM,FLUIDS/ELECTROLYTES W MCC" = "640",
  "641 - MISC DISORDERS OF NUTRITION,METABOLISM,FLUIDS/ELECTROLYTES W/O MCC" = "641",
  "682 - RENAL FAILURE W MCC" = "682",
  "683 - RENAL FAILURE W CC" = "683",
  "684 - RENAL FAILURE W/O CC/MCC" = "684",
  "689 - KIDNEY & URINARY TRACT INFECTIONS W MCC" = "689",
  "690 - KIDNEY & URINARY TRACT INFECTIONS W/O MCC" = "690",
  "811 - RED BLOOD CELL DISORDERS W MCC" = "811",
  "812 - RED BLOOD CELL DISORDERS W/O MCC" = "812",
  "853 - INFECTIOUS & PARASITIC DISEASES W O.R. PROCEDURE W MCC" = "853",
  "871 - SEPTICEMIA OR SEVERE SEPSIS W/O MV 96+ HOURS W MCC" = "871",
  "872 - SEPTICEMIA OR SEVERE SEPSIS W/O MV 96+ HOURS W/O MCC" = "872",
  "897 - ALCOHOL/DRUG ABUSE OR DEPENDENCE W/O REHABILITATION THERAPY W/O MCC" = "897",
  "918 - POISONING & TOXIC EFFECTS OF DRUGS W/O MCC" = "918",
  "948 - SIGNS & SYMPTOMS W/O MCC" = "948",
  "149 - DYSEQUILIBRIUM" = "149",
  "207 - RESPIRATORY SYSTEM DIAGNOSIS W VENTILATOR SUPPORT 96+ HOURS" = "207",
  "303 - ATHEROSCLEROSIS W/O MCC" = "303",
  "314 - OTHER CIRCULATORY SYSTEM DIAGNOSES W MCC" = "314",
  "315 - OTHER CIRCULATORY SYSTEM DIAGNOSES W CC" = "315",
  "331 - MAJOR SMALL & LARGE BOWEL PROCEDURES W/O CC/MCC" = "331",
  "439 - DISORDERS OF PANCREAS EXCEPT MALIGNANCY W CC" = "439",
  "460 - SPINAL FUSION EXCEPT CERVICAL W/O MCC" = "460",
  "698 - OTHER KIDNEY & URINARY TRACT DIAGNOSES W MCC" = "698",
  "699 - OTHER KIDNEY & URINARY TRACT DIAGNOSES W CC" = "699",
  "917 - POISONING & TOXIC EFFECTS OF DRUGS W MCC" = "917",
  "074 - CRANIAL & PERIPHERAL NERVE DISORDERS W/O MCC" = "074",
  "244 - PERMANENT CARDIAC PACEMAKER IMPLANT W/O CC/MCC" = "244",
  "253 - OTHER VASCULAR PROCEDURES W CC" = "253",
  "287 - CIRCULATORY DISORDERS EXCEPT AMI, W CARD CATH W/O MCC" = "287",
  "469 - MAJOR JOINT REPLACEMENT OR REATTACHMENT OF LOWER EXTREMITY W MCC" = "469",
  "473 - CERVICAL SPINAL FUSION W/O CC/MCC" = "473",
  "480 - HIP & FEMUR PROCEDURES EXCEPT MAJOR JOINT W MCC" = "480",
  "491 - BACK & NECK PROC EXC SPINAL FUSION W/O CC/MCC" = "491",
  "602 - CELLULITIS W MCC" = "602",
  "039 - EXTRACRANIAL PROCEDURES W/O CC/MCC" = "039",
  "100 - SEIZURES W MCC" = "100",
  "238 - MAJOR CARDIOVASC PROCEDURES W/O MCC" = "238",
  "246 - PERC CARDIOVASC PROC W DRUG-ELUTING STENT W MCC OR 4+ VESSELS/STENTS" = "246",
  "247 - PERC CARDIOVASC PROC W DRUG-ELUTING STENT W/O MCC" = "247",
  "249 - PERC CARDIOVASC PROC W NON-DRUG-ELUTING STENT W/O MCC" = "249",
  "251 - PERC CARDIOVASC PROC W/O CORONARY ARTERY STENT W/O MCC" = "251",
  "252 - OTHER VASCULAR PROCEDURES W MCC" = "252",
  "254 - OTHER VASCULAR PROCEDURES W/O CC/MCC" = "254",
  "286 - CIRCULATORY DISORDERS EXCEPT AMI, W CARD CATH W MCC" = "286",
  "301 - PERIPHERAL VASCULAR DISORDERS W/O CC/MCC" = "301",
  "371 - MAJOR GASTROINTESTINAL DISORDERS & PERITONEAL INFECTIONS W MCC" = "371",
  "418 - LAPAROSCOPIC CHOLECYSTECTOMY W/O C.D.E. W CC" = "418",
  "467 - REVISION OF HIP OR KNEE REPLACEMENT W CC" = "467",
  "484 - MAJOR JOINT & LIMB REATTACHMENT PROC OF UPPER EXTREMITY W/O CC/MCC" = "484",
  "870 - SEPTICEMIA OR SEVERE SEPSIS W MV 96+ HOURS" = "870",
  "885 - PSYCHOSES" = "885")

shinyUI(
  fluidPage(
    #theme = "bootstrap.css",
    titlePanel(title = "Hospital charge data"), 
    
    hr(),
    
    fluidRow(
      column(2, selectInput("statename", "State:", states, selected='FL')),
      column(10, selectInput("drgcode", "DRG code:", drgs, width = '100%'), offset = 0)
    ),
    
    hr(),
    
    fluidRow(
      column(6, plotOutput("map")),
      column(6, plotOutput("scatterplot"), offset = 0)
      ),
    
    hr()
    
  )
)
